apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
  namespace: santa
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: "580572941932.dkr.ecr.ap-south-1.amazonaws.com/santa/position-simulator:BUILD_ID"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
---
# No service for this microservice - it's "headless", it just sends out data and nothing calls it.
