pipeline {
   agent any

    stages {
        stage('Terraform Init') {
            steps {
                dir('eks_final'){
                    sh 'terraform init -no-color'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('eks_final'){
                    sh 'terraform plan -out terraform.plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('eks_final'){
                    sh 'terraform apply -auto-approve terraform.plan'
                }
            }
        }
    }
}
