pipeline {
   agent any

    stages {
        stage('Terraform Init') {
            steps {
                dir('jenkins'){
                    sh 'terraform init -no-color'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('jenkins'){
                    sh 'terraform plan -out terraform.plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('jenkins'){
                    sh 'terraform apply -auto-approve"'
                }
            }
        }
    }
}