pipeline {
   agent any

   environment {
     // You must set the following environment variables
     ORGANIZATION_NAME="sbatchu1/santa-bootcamp"
     // YOUR_DOCKERHUB_USERNAME (it doesn't matter if you don't have one)
     
    //  SERVICE_NAME = "webapp"
    //  REPOSITORY_TAG="${YOUR_DOCKERHUB_USERNAME}/${ORGANIZATION_NAME}-${SERVICE_NAME}:${BUILD_ID}"
   
     REPOSITORY_ADDRESS = '580572941932.dkr.ecr.ap-south-1.amazonaws.com'
     CONTAINER_IMAGE = 'santa/queue'
     K8S_NAME="santa-eks-u7Gvgv9k"
     APP_NAME = 'queue' 
   }

   stages {

      stage('Prepare') {
         steps {
             dir("${APP_NAME}"){
                sh '$(aws ecr get-login --no-include-email --region ap-south-1)'
             }
           
         }
      }

      stage('Build Image') {
         steps {
             dir(APP_NAME){
                sh "docker build\
                    --cache-from $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:latest\
                    --tag $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:latest\
                    --tag $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:${BUILD_ID} ."
                }
         }
      }

    stage('Publish') {
        steps {
            dir(APP_NAME){               
                sh "docker push $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:${BUILD_ID}"
            }
        }
    }
      

      stage('Deploy to Cluster') {
          steps {
            dir(APP_NAME){
                sh "aws eks --region ap-south-1 update-kubeconfig --name $K8S_NAME"
                sh 'sed -i "s/BUILD_ID/${BUILD_ID}/g" deploy.yaml'
                sh 'sudo kubectl apply -f deploy.yaml'
            }
          }
      }
   }
}
