apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: santa
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        image: "580572941932.dkr.ecr.ap-south-1.amazonaws.com/santa/webapp:BUILD_ID"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  namespace: santa
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

  type: LoadBalancer
