pipeline {
   agent any

   environment {
     // You must set the following environment variables
     ORGANIZATION_NAME="sbatchu1/santa-bootcamp"
     // YOUR_DOCKERHUB_USERNAME (it doesn't matter if you don't have one)
     
    //  SERVICE_NAME = "webapp"
    //  REPOSITORY_TAG="${YOUR_DOCKERHUB_USERNAME}/${ORGANIZATION_NAME}-${SERVICE_NAME}:${BUILD_ID}"

     REPOSITORY_ADDRESS = '580572941932.dkr.ecr.ap-south-1.amazonaws.com'
     CONTAINER_IMAGE = 'santa/webapp'
     K8S_NAME="santa-eks-u7Gvgv9k"
   }

   stages {

      stage('Prepare') {
         steps {
             dir('webapp'){
                sh '$(aws ecr get-login --no-include-email --region ap-south-1)'
             }
           
         }
      }

      stage('Build Image') {
         steps {
             dir('webapp'){
                sh "docker build\
                    --cache-from $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:latest\
                    --tag $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:latest\
                    --tag $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:${BUILD_ID} ."
                }
         }
      }

    stage('Publish') {
        steps {
            dir('webapp'){
                sh "docker push $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:latest"
                sh "docker push $REPOSITORY_ADDRESS/$CONTAINER_IMAGE:${BUILD_ID}"
            }
        }
    }
      

      stage('Deploy to Cluster') {
          steps {
            dir('webapp'){
                sh "aws eks --region ap-south-1 update-kubeconfig --name $K8S_NAME"
                sh 'sudo kubectl cluster-info dump'
                sh 'sudo kubectl get nodes'
                sh 'kubectl apply -f deploy.yaml'
            }
          }
      }
   }
}
